### ISSUE TITLE
Error with kodi

### ISSUE THREAD

**Issue by misiaty** [maximeh/script.myepisodes#12]
Hi, when I start Kodi (15) I get an error in log file:

08:30:00 T:5600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\£ukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 185, in <module>
                                                player = Player()
                                              File "C:\Users\£ukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 36, in __init__
                                                self.mye = self._loginMyEpisodes()
                                              File "C:\Users\£ukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 91, in _loginMyEpisodes
                                                notif(login_notif, time=2500)
                                              File "C:\Users\£ukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 172, in notif
                                                notif_msg = "%s, %s, %i, %s" % ('MyEpisodes', msg, time, __icon__)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by maximeh** [comment]
Hi,

Thanks a lot for your report.
I've pushed a new commit but I haven't tested it. Would you be so kind to test it ?
As you may have guessed, it has to do with the '£' in your username so it's a bit hard for me to test.

**Comment by maximeh** [comment]
@misiaty ping ?

**Comment by misiaty** [comment]
Sorry for my late answer.

Downloaded script from github (no next version number?) and nothing change, maybe I'm doing something wrong... I'm new on github.

**Comment by maximeh** [comment]
@misiaty Did you downloaded the lastest 1.2.1 that I released this morning ?

**Comment by misiaty** [comment]
12:40:49 T:5980  NOTICE: script.grab.fanart: Grab Fanart Service Started
12:40:50 T:10156   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 200, in <module>
                                                player = Player()
                                              File "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 35, in __init__
                                                self.mye = self._loginMyEpisodes()
                                              File "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 90, in _loginMyEpisodes
                                                notif(login_notif, time=2500)
                                              File "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 178, in notif
                                                time, __icon__)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)
                                            -->End of Python script error report<--


Still the same

**Comment by maximeh** [comment]
Thanks a lot. I will try to fix this once for all so you can use the addon.
I'll report back when it's done.

**Comment by castorfou** [comment]
I have the same issue with both version 1.0.15 and version 1.2.1 (which cannot be installed)

**Comment by maximeh** [comment]
Why can't you install 1.2.1 ?

**Comment by castorfou** [comment]
don't know why but here is the error message :

23:06:46 T:140339037849344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 18: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/guillaume/.kodi/addons
/script.myepisodes/default.py", line 200, in <module>
                                                player = Player()
                                              File "/home/guillaume/.kodi/addons/script.myepisodes/default.py", line 35, in __init__
                                                self.mye = self._loginMyEpisodes()
                                              File "/home/guillaume/.kodi/addons/script.myepisodes/default.py", line 90, in _loginMyEpisodes
                                                notif(login_notif, time=2500)
                                              File "/home/guillaume/.kodi/addons/script.myepisodes/default.py", line 177, in notif
                                                msg.decode('utf-8', "replace"),
                                              File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 18: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by castorfou** [comment]
As a workaround I have changed an entry in resources/language/French/strings.po

Moved from 
msgctxt "#32911"
msgid "connected"
msgstr "connecté"

to
msgctxt "#32911"
msgid "connected"
msgstr "connecte"

The special character é is causing some problem here.

**Comment by maximeh** [comment]
@misiaty @castorfou I've just published a pre-release 1.2.2 which should hopefully fix your issues.

I'll wait on your report before announcing this one as the latests official.

**Comment by castorfou** [comment]
@maximeh installation has worked for me. I will report further issues if any

**Comment by maximeh** [comment]
If you could report if it works for you now it would be great too.

**Comment by misiaty** [comment]
I will test it tomorrow and report.

**Comment by misiaty** [comment]
:(
still not working...

13:31:25 T:2444   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 199, in <module>
                                                player = Player()
                                              File "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 35, in __init__
                                                self.mye = self._loginMyEpisodes()
                                              File "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 90, in _loginMyEpisodes
                                                notif(login_notif, time=2500)
                                              File "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\script.myepisodes\default.py", line 176, in notif
                                                notif_msg = "%s, %s, %i, %s" % ('MyEpisodes', msg, time, __icon__)
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)
                                            -->End of Python script error report<--
13:31:34 T:6700  NOTICE: Thread BackgroundLoader start, auto delete: false
13:31:53 T:8524  NOTICE: Previous line repeats 2 times.
13:31:53 T:8524  NOTICE: Storing total System Uptime
13:31:53 T:8524  NOTICE: Saving settings
13:31:53 T:8524  NOTICE: stop all
13:31:53 T:8524  NOTICE: stop player
13:31:53 T:8524  NOTICE: ES: Stopping event server
13:31:53 T:8524  NOTICE: stopping upnp
13:31:54 T:2140  NOTICE: ES: UDP Event server stopped
13:31:54 T:8524  NOTICE: stop sap announcement listener
13:31:54 T:8524  NOTICE: clean cached files!
13:31:54 T:8524  NOTICE: unload skin
13:31:54 T:8524 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture button-nofocus.png
13:31:54 T:8524 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture button-focus.png
13:31:56 T:1340 WARNING: CPythonInvoker(2, C:\Users\Ĺukasz\AppData\Roaming\Kodi\addons\service.skin.widgets\default.py): the python script "C:\Users\Ĺukasz\AppData\Roaming\Kodi\addons\service.skin.widgets\default.py" has left several classes in memory that we couldn't clean up. The classes include: class PythonBindings::XBMCAddon_xbmc_Player_Director,class XBMCAddon::xbmcgui::Window,class PythonBindings::XBMCAddon_xbmc_Monitor_Director
13:31:57 T:2504 WARNING: CPythonInvoker(6, C:\Users\Ĺukasz\AppData\Roaming\Kodi\addons\service.library.data.provider\service.py): the python script "C:\Users\Ĺukasz\AppData\Roaming\Kodi\addons\service.library.data.provider\service.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::Window,class PythonBindings::XBMCAddon_xbmc_Monitor_Director,class PythonBindings::XBMCAddon_xbmc_Player_Director
13:31:58 T:5072  NOTICE: script.tv.show.next.aired: ### abort requested -- stopping background processing
13:31:58 T:8524  NOTICE: stopped
13:31:58 T:8524  NOTICE: destroy
13:31:58 T:8524  NOTICE: closing down remote control service
13:31:58 T:8524  NOTICE: unload sections

**Comment by maximeh** [comment]
If you look at the version of the plugin, you are using the 1.2.1 right ?

**Comment by misiaty** [comment]
1.2.2

**Comment by maximeh** [comment]
Hm.... Could you paste me the username that you use ? Because it's cleary
what is problematic here. I tried to reproduce using out of ASCII character
and I succeded, but the patch I pushed fix the issues on my setup :/.

**Comment by misiaty** [comment]
in Windows - Łukasz
in MyEpisodes -aXe

**Comment by maximeh** [comment]
Thanks, I'll try tonight to reproduce and hopefully fix this...

**Comment by maximeh** [comment]
The character which is causing trouble is https://en.wikipedia.org/wiki/Å
It should be in you username from the line in the code where it breaks, is this character into your username ?

**Comment by misiaty** [comment]
No... it's not a character from my username, but in my username is other non-english character

https://en.wikipedia.org/wiki/%C5%81

**Comment by maximeh** [comment]
Ah yes, I should have checked this char, there's the 0xC5 that is causing
trouble. I keep looking, I feel like the code is doing the right things (it
works fine with french accent, which are out of the ASCII scope), but I am
surely missing something here.
Really interesting issue, sorry that it bothers you this long :/.

**Comment by maximeh** [comment]
I think I have finally found the issue. It's pretty silly now that I think about it.
The "problem" is that your username (on your machine, not on myepisodes) contains a non ASCII character, and when the addon display a notification, it displays it with an icon. To display the icon, we need its path, and the path contains the offending char.

Try the latest pre-release. Hopefully this shoud finally fix your issue.

**Comment by misiaty** [comment]
Ok, now this issue is fixed... but now I get Login failed and I'm 100% sure using the same info as on the web site... sad :(

**Comment by maximeh** [comment]
Yes... The site has changed some other it appears. Since there's no API, it
really hackish to discuss with MyEpisodes.

Thanks for reporting this. I already have it fixed, I'll push a newer
pre-release in the next minutes. If you could test it on your side and
report here so that I could close this issue.

**Comment by misiaty** [comment]
1.2.4 - still login failed (username and password contains only ascii characters)

**Comment by maximeh** [comment]
Could you active the debug in Kodi, and send me your log ? It appears to be
working for me at the moment so I'll need more information.

**Comment by misiaty** [comment]
http://pastebin.com/6ik0t29d

**Comment by maximeh** [comment]
I don't see anything wrong with your log.
I assume you are able to login through using the website ? I'll check again
using Kodi tonight, testing the code itself appears to be working with my
account, so maybe there's an issue with the way it works with Kodi.

**Comment by maximeh** [comment]
I tried with Kodi and my credentials, I did not had trouble connecting, nor marking a show as watched. 

Try to log to the website, if it works fine for you, we'll try to do some more testing/debugging. It's going to be a little harder since there's no error for me to look at :/

What you can do is add this code in [...]/resources/lib/myepisodes.py right after theses two lines:
```python
        login_url = "%s/%s" % (MYEPISODE_URL, "login.php?action=login")         
        data = self.send_req(login_url, login_data)            
```

And add (respect the indentation or it won't work, use space only, there should be 8 space before 'p'):
```python
        print data
```
Try to start Kodi as usual, and paste the relevant log please (or the whole log, at your convenience).
This will dump the whole HTML page you receive from MyEpisodes after your tried to login. This should help me to understand what's going on.

Again thanks a lot for your patience and your help !

**Comment by castorfou** [comment]
version 1.2.4 has worked for me.
print data displays my list of episodes.
I am watching a short episode of southpark to confirm it will set as watched in myepisodes website.

**Comment by maximeh** [comment]
@misiaty is it still broken for you ?

**Comment by misiaty** [comment]
My log

```
11:20:19 T:8476  NOTICE: special://profile/ is mapped to: special://masterprofile/
11:20:19 T:8476  NOTICE: -----------------------------------------------------------------------
11:20:19 T:8476  NOTICE: Starting Kodi (15.1 Git:20150816-f4dda26). Platform: Windows NT x86 32-bit
11:20:19 T:8476  NOTICE: Using Release Kodi x32 build
11:20:19 T:8476  NOTICE: Kodi compiled Aug 16 2015 by MSVC 180030723 for Windows NT x86 32-bit version 6.0 (0x06000000)
11:20:19 T:8476  NOTICE: Running on LENOVO 20238 with Windows 8.1, kernel: Windows NT x86 64-bit version 6.3
11:20:19 T:8476  NOTICE: Host CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz, 8 cores available
11:20:19 T:8476  NOTICE: Desktop Resolution: 1366x768 32Bit at 60Hz
11:20:19 T:8476  NOTICE: Running with restricted rights
11:20:19 T:8476  NOTICE: Aero is enabled
11:20:19 T:8476  NOTICE: special://xbmc/ is mapped to: C:\Program Files (x86)\Kodi
11:20:19 T:8476  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files (x86)\Kodi
11:20:19 T:8476  NOTICE: special://masterprofile/ is mapped to: C:\Users\Łukasz\AppData\Roaming\Kodi\userdata
11:20:19 T:8476  NOTICE: special://home/ is mapped to: C:\Users\Łukasz\AppData\Roaming\Kodi\
11:20:19 T:8476  NOTICE: special://temp/ is mapped to: C:\Users\Łukasz\AppData\Roaming\Kodi\cache
11:20:19 T:8476  NOTICE: The executable running is: C:\Program Files (x86)\Kodi\Kodi.exe
11:20:19 T:8476  NOTICE: Local hostname: LaptopW8
11:20:19 T:8476  NOTICE: Log File is located: C:\Users\Łukasz\AppData\Roaming\Kodi\kodi.log
11:20:19 T:8476  NOTICE: -----------------------------------------------------------------------
11:20:19 T:8476  NOTICE: load settings...
11:20:19 T:8476 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
11:20:19 T:8476 WARNING: CSettingString: unknown options filler "timezones" of "locale.timezone"
11:20:19 T:8476  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
11:20:19 T:8476  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
11:20:19 T:8476  NOTICE: Default DVD Player: dvdplayer
11:20:19 T:8476  NOTICE: Default Video Player: dvdplayer
11:20:19 T:8476  NOTICE: Default Audio Player: paplayer
11:20:19 T:8476  NOTICE: Disabled debug logging due to GUI setting. Level 0.
11:20:19 T:8476  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
11:20:19 T:8476  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
11:20:19 T:8476  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
11:20:19 T:8476  NOTICE: Loaded playercorefactory configuration
11:20:19 T:8476  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
11:20:19 T:8476  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
11:20:19 T:7400  NOTICE: Thread ActiveAE start, auto delete: false
11:20:19 T:3660  NOTICE: Thread AESink start, auto delete: false
11:20:19 T:7400  NOTICE: Found 2 Lists of Devices
11:20:19 T:7400  NOTICE: Enumerated DIRECTSOUND devices:
11:20:19 T:7400  NOTICE:     Device 1
11:20:19 T:7400  NOTICE:         m_deviceName      : {8659AAA6-9D67-46CB-BFFF-3601DA99CA77}
11:20:19 T:7400  NOTICE:         m_displayName     : Speakers - Głośniki (Conexant SmartAudio HD)
11:20:19 T:7400  NOTICE:         m_displayNameExtra: DIRECTSOUND: Głośniki (Conexant SmartAudio HD)
11:20:19 T:7400  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:20:19 T:7400  NOTICE:         m_channels        : FL,FR
11:20:19 T:7400  NOTICE:         m_sampleRates     : 48000
11:20:19 T:7400  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
11:20:19 T:7400  NOTICE:     Device 2
11:20:19 T:7400  NOTICE:         m_deviceName      : default
11:20:19 T:7400  NOTICE:         m_displayName     : default
11:20:19 T:7400  NOTICE:         m_displayNameExtra:
11:20:19 T:7400  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:20:19 T:7400  NOTICE:         m_channels        : FL,FR
11:20:19 T:7400  NOTICE:         m_sampleRates     : 48000
11:20:19 T:7400  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
11:20:19 T:7400  NOTICE: Enumerated WASAPI devices:
11:20:19 T:7400  NOTICE:     Device 1
11:20:19 T:7400  NOTICE:         m_deviceName      : {8659AAA6-9D67-46CB-BFFF-3601DA99CA77}
11:20:19 T:7400  NOTICE:         m_displayName     : Speakers - Głośniki (Conexant SmartAudio HD)
11:20:19 T:7400  NOTICE:         m_displayNameExtra: WASAPI: Głośniki (Conexant SmartAudio HD)
11:20:19 T:7400  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:20:19 T:7400  NOTICE:         m_channels        : FL,FR
11:20:19 T:7400  NOTICE:         m_sampleRates     : 192000,96000,48000,44100
11:20:19 T:7400  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
11:20:19 T:7400  NOTICE:     Device 2
11:20:19 T:7400  NOTICE:         m_deviceName      : default
11:20:19 T:7400  NOTICE:         m_displayName     : default
11:20:19 T:7400  NOTICE:         m_displayNameExtra:
11:20:19 T:7400  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:20:19 T:7400  NOTICE:         m_channels        : FL,FR
11:20:19 T:7400  NOTICE:         m_sampleRates     : 192000,96000,48000,44100
11:20:19 T:7400  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
11:20:19 T:8476  NOTICE: Running database version Addons19
11:20:19 T:8476  NOTICE: ADDONS: Using repository repository.xbmc.org
11:20:19 T:8476  NOTICE: ADDONS: Using repository repository.sd-xbmc.org
11:20:19 T:8476  NOTICE: ADDONS: Using repository superrepo.kodi.isengard.repositories
11:20:19 T:8476  NOTICE: ADDONS: Using repository superrepo.kodi.helix.all
11:20:19 T:8476  NOTICE: ADDONS: Using repository repository.smuto
11:20:19 T:8476  NOTICE: ADDONS: Using repository superrepo.kodi.isengard.skins
11:20:19 T:8348  NOTICE: Thread PeripBusCEC start, auto delete: false
11:20:19 T:8380  NOTICE: Thread PeripBusUSB start, auto delete: false
11:20:19 T:6076  NOTICE: Thread RemoteControl start, auto delete: false
11:20:19 T:8476  NOTICE: Found screen: Generic PnP Monitor on Intel(R) HD Graphics 4600, adapter 0.
11:20:19 T:8476  NOTICE: Primary mode: 1366x768@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Additional mode: 320x200@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 320x240@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 400x300@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 512x384@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 640x400@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 640x480@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 800x600@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 1024x768@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 1280x600@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 1280x720@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 1280x768@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 1360x768@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Previous line repeats 2 times.
11:20:19 T:8476  NOTICE: Additional mode: 1366x768@ 60.00 - Full Screen
11:20:19 T:8476  NOTICE: Checking resolution 16
11:20:19 T:8476  NOTICE: Running database version Addons19
11:20:19 T:8476  NOTICE: Running database version ViewModes6
11:20:19 T:8476  NOTICE: Running database version Textures13
11:20:19 T:8476  NOTICE: Running database version MyMusic52
11:20:19 T:8476  NOTICE: Running database version MyVideos93
11:20:19 T:8476  NOTICE: Running database version TV29
11:20:19 T:8476  NOTICE: Running database version Epg10
11:20:19 T:8476 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
11:20:19 T:8476 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
11:20:19 T:8476 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
11:20:19 T:8476 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
11:20:19 T:7016  NOTICE: Thread LanguageInvoker start, auto delete: false
11:20:19 T:8476  NOTICE: Previous line repeats 9 times.
11:20:19 T:8476  NOTICE: initialize done
11:20:19 T:5920  NOTICE: Thread LanguageInvoker start, auto delete: false
11:20:19 T:8476  NOTICE: CJoystick::EnumJoysticksCallback : Enabled Joystick: Gamepad
11:20:19 T:8476  NOTICE: CJoystick::EnumJoysticksCallback : Total Axis: 4 Total Hats: 1 Total Buttons: 16
11:20:19 T:8476  NOTICE: Running the application...
11:20:19 T:7016  NOTICE: -->Python Interpreter Initialized<--
11:20:19 T:5332  NOTICE: Thread JobWorker start, auto delete: true
11:20:19 T:8476  NOTICE: starting upnp client
11:20:19 T:8476  NOTICE: ES: Starting event server
11:20:19 T:6540  NOTICE: Thread EventServer start, auto delete: false
11:20:19 T:6540  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
11:20:19 T:6540  NOTICE: UDP: Listening on port 9777
11:20:19 T:6552  NOTICE: Thread TCPServer start, auto delete: false
11:20:19 T:5696  NOTICE: Thread JobWorker start, auto delete: true
11:20:19 T:6444  NOTICE: Previous line repeats 1 times.
11:20:19 T:6444  NOTICE: Thread RSSReader start, auto delete: false
11:20:19 T:7208  NOTICE: Thread LanguageInvoker start, auto delete: false
11:20:20 T:6528  NOTICE: -->Python Interpreter Initialized<--
11:20:20 T:3664  NOTICE: Previous line repeats 9 times.
11:20:20 T:3664  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting background proc (6.0.14)
11:20:20 T:7208  NOTICE: -->Python Interpreter Initialized<--
11:20:20 T:6784  NOTICE: script.grab.fanart: Grab Fanart Service Started
11:20:24 T:7888  NOTICE: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
                                                        "http://www.w3.org/TR/html4/loose.dtd">
                                            <html>
                                            	<head>
                                            		<meta name="description" content="MyEpisodes is your personal TV assistant with alot of loved features including episodes checklist, rss feeds, automatic state view, calendar and more. You'll love this website as you will travel through its features. ">
                                            		<meta name="keywords" content="MyEpisodes, My Episodes, SeriesWatch, Series Watch, TvTome, TV.com, TV, tv, assistant, series, tracker, efnet, love, calendar, my episodes, tvtome">
                                            		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                                            
                                            				
                                            		<title>Main Page - MyEpisodes.com</title>
                                            		<link rel="stylesheet" href="/clientscripts/jquery-ui-1.11.4.custom/jquery-ui.css">
                                            		<link rel="stylesheet" href="/myepisodes.css" type="text/css">
                                            		<link rel="shortcut icon" href="/favicon.ico" />
                                            
                                            		<script src="/clientscripts/jquery-1.11.3.min.js"></script>			
                                            		<script src="/clientscripts/jquery-ui-1.11.4.custom/jquery-ui.min.js"></script>
                                            		<script language="javascript" type="text/javascript" src="/clientscripts/scripts.js"></script>
                                            		<script language="javascript" type="text/javascript">
                                            		$(document).ready(function(){
                                            			function acAddShow(item){
                                            				var obj = $(this);
                                            				$.ajax({
                                            					url: '/ajax/service.php?mode=show_manage',
                                            					type: 'POST',
                                            					dataType: 'json',
                                            					data: {
                                            						showid : item.data.id,
                                            						action : 'add'
                                            					},
                                            					success: function(data) {
                                            						obj.removeClass('ac_add_hover').addClass('ac_added');
                                            					}
                                            				});
                                            				item.stopPropagation();
                                            			};
                                            
                                            			var acGlobalSearch = $('#acGlobalSearch').autocomplete({
                                            				source: function(request, response){
                                            					$.ajax({
                                            						url: '/ajax/service.php?mode=search_showname',
                                            						type: 'POST',
                                            						dataType: 'json',
                                            						data: {
                                            							search: request.term
                                            						},
                                            						success: function(data){
                                            							//response(data)
                                            							response($.map(data, function(item){
                                            								return {
                                            									label: item.name,
                                            									value: item.name,
                                            									name: item.name,
                                            									id: item.id,
                                            									added: item.added
                                            								}
                                            							}));
                                            						}
                                            					});
                                            				},
                                            				minLength: 2,
                                            				delay: 500,
                                            				select: function(event, ui) {
                                            					if (ui.item)
                                            					{
                                            						window.location.href = '/show/id-'+ui.item.id+'/';
                                            					}
                                            				}
                                            			});
                                            
                                            			acGlobalSearch.autocomplete("instance")._renderItem = function(ul, item) {
                                            				var span = $("<span></span>").addClass(item.added ? 'ac_added' : 'ac_add');
                                            				span.on('click', item, acAddShow);
                                            				span.on('mouseover', function(){
                                            					$(this).removeClass("ac_add").addClass("ac_add_hover")
                                            				});
                                            				span.on('mouseout', function(){
                                            					$(this).removeClass("ac_add_hover").addClass("ac_add")
                                            				});
                                            
                                            				var elm = $("<li>")
                                            					.append(item.name)
                                            					.append(span);
                                            				elm.appendTo(ul);
                                            				return elm;
                                            			};
                                            		});
                                            
                                            			function MenuText(sectionName)
                                            			{
                                            				if (sectionName == 'myshows')
                                            				{
                                            					getElmById('menuText').innerHTML = '<a href="/myshows/manage/">Manage Shows</a> :: <a href="/myshows/list/">Show Overview</a> :: <a href="/epslist/">Episodes List</a> :: <a href="/allinone/">All-In-One!</a> :: <a href="/cal/">Calendar</a> :: <a href="/quickcheck/">Quick Check</a> :: <a href="/countdown/">Countdown</a> :: <a href="/timewasted/">Time Wasted</a> :: <a href="/shows/">All Shows</a></a>';
                                            				}
                                            				else if (sectionName == 'system')
                                            				{
                                            					getElmById('menuText').innerHTML = '<a href="/stats.php?type=site">Monthly Stats</a> :: <a href="/stats.php?type=general">Today\'s Stats</a> :: <a href="/stats.php?type=today">Airing Today</a> :: <a href="/stats.php?type=topshows">Best Shows</a>';
                                            				}
                                            				else if (sectionName == 'profile')
                                            				{
                                            					getElmById('menuText').innerHTML = '<a href="/cp.php">Control Panel</a> :: <a href="/rsshelp.php">RSS Feeds</a> :: <a href="/mysig.php">My Signature</a> :: <a href="/forum/viewtopic.php?t=19">Request a Feature</a>';
                                            				}
                                            				else if (sectionName == 'personal')
                                            				{
                                            									}
                                            			}
                                            		</script>
                                            		<script type="text/javascript">
                                            			var _gaq = _gaq || [];
                                            			_gaq.push(['_setAccount', 'UA-27298469-1']);
                                            			_gaq.push(['_setDomainName', 'myepisodes.com']);
                                            			_gaq.push(['_setAllowLinker', true]);
                                            			_gaq.push(['_trackPageview']);
                                            
                                            			(function() {
                                            				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                                            				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                                            				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                                            			})();
                                            		</script>
                                            	</head>
                                            	<body>
                                            		<table align="center">
                                            		<tr>
                                            			<td width="50%" style="vertical-align: top;">
                                            			</td>
                                            			<td width="760px" style="vertical-align: top;">
                                            	<div id="divContainer">
                                            		<div id="divAboveMenu">
                                            			<div id="tag">
                                            				<a href="/login.php">Change Login</a> /
                                            <a href="/login.php?action=logout"><strong>aXe</strong> (Logout)</a><!--
                                            				<br>
                                            				<br>
                                            				<form action="https://www.paypal.com/cgi-bin/webscr" method="post" style="margin: 0; padding: 0; display:inline;"><input type="hidden" name="cmd" value="_s-xclick"><input type="image" src="/img/donateUSD.jpg" border="0" name="submit" alt="Make payments with PayPal - it\'s fast, free and secure!"><input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHLwYJKoZIhvcNAQcEoIIHIDCCBxwCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYBbtAm7ZWs8TPUXWj+yHG0Hlg1wa1gDFVOUd7E6SxHYN/Vr2H2IXwNDDwSABxDr14LUgAA3b6D9SUBIqL3xMhNMScUakyZ63gZjyUrFBeZ8R7z5Gkxg2t4B179X8KfnVz9j1GaE8rTBHZe5eFO8E0PeiHXXDlP8hCVB/K50tD/PejELMAkGBSsOAwIaBQAwgawGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQI5W4DknqGKMCAgYhuUxt99zoxHetz4taA+fC49a2Kvp/d9nj1FTdHm8251c5vJH+DNhiuSSHN3uoIRFMU/2OQQ6oKqOYDKJQc7jlGUGPobqnVHcU/6kBU0XvSyCBNV7x5SF17h4vSde5Za9AN/Cu3gzy7W/ho377RbKDxZ9Zs4GDjFH2QN790Q6Bf8cq6D9cD4bCToIIDhzCCA4MwggLsoAMCAQICAQAwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMB4XDTA0MDIxMzEwMTMxNVoXDTM1MDIxMzEwMTMxNVowgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBR07d/ETMS1ycjtkpkvjXZe9k+6CieLuLsPumsJ7QC1odNz3sJiCbs2wC0nLE0uLGaEtXynIgRqIddYCHx88pb5HTXv4SZeuv0Rqq4+axW9PLAAATU8w04qqjaSXgbGLP3NmohqM6bV9kZZwZLR/klDaQGo1u9uDb9lr4Yn+rBQIDAQABo4HuMIHrMB0GA1UdDgQWBBSWn3y7xm8XvVk/UtcKG+wQ1mSUazCBuwYDVR0jBIGzMIGwgBSWn3y7xm8XvVk/UtcKG+wQ1mSUa6GBlKSBkTCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb22CAQAwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQCBXzpWmoBa5e9fo6ujionW1hUhPkOBakTr3YCDjbYfvJEiv/2P+IobhOGJr85+XHhN0v4gUkEDI8r2/rNk1m0GA8HKddvTjyGw/XqXa+LSTlDYkqI8OwR8GEYj4efEtcRpRYBxV8KxAW93YDWzFGvruKnnLbDAF6VR5w/cCMn5hzGCAZowggGWAgEBMIGUMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbQIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMDUxMDA1MTkwODIyWjAjBgkqhkiG9w0BCQQxFgQUSXCAhKtLIUh1s3VQB259R4erpH8wDQYJKoZIhvcNAQEBBQAEgYB4QJL5rE2do/ta9Fv5urQMMNx0Gujoaf1SE8ED2M3SVrY1iqxwKKITI4NKfMLohvUpzDEq1EKnidmNoZd0WAZvRR8NAGYWpfrIUGHxoKXmz+iQ3ZE5t0h61FhXA24t21q9CHg+zJ1AN1BGU6D1H9XdcU/yeLGOpQCKEOC5hX5lfA==-----END PKCS7-----"></form>
                                            				<form action="https://www.paypal.com/cgi-bin/webscr" method="post" style="margin-left: 10px; padding: 0;display:inline;"><input type="hidden" name="cmd" value="_s-xclick"><input type="image" src="/img/donateEUR.jpg" border="0" name="submit" alt="Make payments with PayPal - it\'s fast, free and secure!"><input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHLwYJKoZIhvcNAQcEoIIHIDCCBxwCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCntiohyUEZrmMe+D8Vp4U5eak/mFYgGNsac8zPyB+lCxYaISmnBiLpyhry6dbP7vzssTB4SE73VDq95cIMS4jUjsIu4dy1bdf5V44K9NnUCkf61CPAAwIrubmAy8ZNsKMtNop0z6tAmBYB1tVtp2UW3LQiZLaILGFyzUaBi2ceEjELMAkGBSsOAwIaBQAwgawGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIqZW/sJShNl2AgYhy7ap4FXZeBj4n821CHJ6IgVjiWJU2HguJO2SihrwB1pQAO6Up2DcSiL75G7g8rtwAWeVvx/mwldxSl6kX0xb5ALPVuCnwVdY8bLtpSIH9dm0hnFe4HzdDrrs338kskO3RuRP7JUwyDSyyh8WF6hZ4nolmP685YKt8GFXoyjLGZMfarGpR9csSoIIDhzCCA4MwggLsoAMCAQICAQAwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMB4XDTA0MDIxMzEwMTMxNVoXDTM1MDIxMzEwMTMxNVowgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBR07d/ETMS1ycjtkpkvjXZe9k+6CieLuLsPumsJ7QC1odNz3sJiCbs2wC0nLE0uLGaEtXynIgRqIddYCHx88pb5HTXv4SZeuv0Rqq4+axW9PLAAATU8w04qqjaSXgbGLP3NmohqM6bV9kZZwZLR/klDaQGo1u9uDb9lr4Yn+rBQIDAQABo4HuMIHrMB0GA1UdDgQWBBSWn3y7xm8XvVk/UtcKG+wQ1mSUazCBuwYDVR0jBIGzMIGwgBSWn3y7xm8XvVk/UtcKG+wQ1mSUa6GBlKSBkTCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb22CAQAwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQCBXzpWmoBa5e9fo6ujionW1hUhPkOBakTr3YCDjbYfvJEiv/2P+IobhOGJr85+XHhN0v4gUkEDI8r2/rNk1m0GA8HKddvTjyGw/XqXa+LSTlDYkqI8OwR8GEYj4efEtcRpRYBxV8KxAW93YDWzFGvruKnnLbDAF6VR5w/cCMn5hzGCAZowggGWAgEBMIGUMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbQIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMDUxMDA1MTkwOTI2WjAjBgkqhkiG9w0BCQQxFgQU51unfCfJJrxKS2z8cArydqEdXWQwDQYJKoZIhvcNAQEBBQAEgYAf0qxTFRKwjC0L3McgHVmFS4xfCe+Wm3CZNG8k5kjvw8wz9LOB5+o+jEiazAGLIZVJCPxf9Snr5leUfv/AC8u+/UJImx8nPp6aedZUzjAHLga894HPizqp1Xq4oz3u96NkdXFRvOQbPskEY2rMXJQlUCxfoYoQ5lnyn3mS+bn9uw==-----END PKCS7-----"></form>
                                            -->
                                            			</div>
                                            			<div style="clear: right; float: right; margin-top: 5px; margin-right: 3px;">
                                            				<!-- Banner -->
                                            			</div>
                                            			<div style="position: absolute; bottom: 0px; right: 0px;">
                                            				<form action="/search/" method="post" id="globalsearch">
                                            					<input type="text" id="acGlobalSearch" name="tvshow">
                                            					<input type="submit" name="action" value="Search" class="flatButton">
                                            				</form>
                                            			</div>
                                            			<a href="/frontpage/"><img src="/img/myepisodes_logo.jpg" alt="logo" border="0"></a>
                                            		</div>
                                            		<div id="divMenu">
                                            		<ul id="navlist">
                                            			<li class="mmli">
                                            				<a href="/frontpage/"><img border="0" src="/img/menu_top_home.jpg"></a>
                                            			</li>
                                            			<li class="mmli" onclick="javascript:MenuText('myshows');">
                                            				<img border="0" src="/img/menu_top_myshows.jpg">
                                            			</li>
                                            			<li class="mmli" onclick="javascript:MenuText('profile');">
                                            				<img border="0" src="/img/menu_top_profile.jpg">
                                            			</li>
                                            					<li class="mmli" onclick="javascript:MenuText('system');">
                                            				<img border="0" src="/img/menu_top_system.jpg">
                                            			</li>
                                            			<li class="mmli">
                                            				<a href="/forum/"><img border="0" src="/img/menu_top_forum.jpg"></a>
                                            			</li>
                                            			<li class="mmli">
                                            				<a href="/donate.php"><img border="0" src="/img/menu_top_donate.jpg"></a>
                                            			</li>
                                            		</ul></div>
                                            		<div id="menuText">
                                            		</div>
                                            		<script language="javascript">
                                            			MenuText('myshows');
                                            		</script>
                                            		<br>
                                            		<div align="center">
                                            			<b>MyEpisodes</b> - Your own personal TV assistant.
                                            		</div>
                                            		<ul>
                                            			<li>Keep track of as many shows as you like with a fast, easy and user-friendly interface.</li>
                                            			<li>Have total control over your episodes.</li>
                                            			<li>Have it all for <b>free</b>, but feel free to <b>donate</b> ;)</li>
                                            		</ul>
                                            				<br><br>
                                            <img src="/img/header_todays_shows.jpg"><br><ul><li><a href="/epsbyshow/3212/71 Grader Nord"><b>71 Grader Nord S17E09</b></a> "Episode 9"</li><li><a href="/epsbyshow/13721/Ace of Diamond"><b>Ace of Diamond S02E30</b></a> "The Kings' Roar"</li><li><a href="/epsbyshow/3896/Antiques Roadshow (US)"><b>Antiques Roadshow (US) S19E31</b></a> "Chicago (Hour Two)"</li><li><a href="/epsbyshow/8856/Awkward"><b>Awkward S05E09</b></a> "Say No To The Dress"</li><li><a href="/epsbyshow/14744/Beat Bobby Flay"><b>Beat Bobby Flay S06E05</b></a> "Trick Or Sweet"</li><li><a href="/epsbyshow/16506/Blindspot"><b>Blindspot S01E06</b></a> "Cede Your Soul"</li><li><a href="/epsbyshow/9467/Brain Games"><b>Brain Games S06E07</b></a> "Try This At Home"</li><li><a href="/epsbyshow/17737/Bureau Raampoort"><b>Bureau Raampoort S01E06</b></a> "De studente"</li><li><a href="/epsbyshow/18102/Buying the Yukon"><b>Buying the Yukon S01E10</b></a> "360 Degree Mountain Views"</li><li><a href="/epsbyshow/5888/Canada's Worst Driver"><b>Canada's Worst Driver S11E01</b></a> "Ready, Set, Go!"</li><li><a href="/epsbyshow/7300/Conan"><b>Conan S2015E132</b></a> "Brent Morin, Warren Haynes"</li><li><a href="/epsbyshow/2789/Coronation Street"><b>Coronation Street S56E214</b></a> "Mon Oct 26 2015 Part 1"</li><li><a href="/epsbyshow/2789/Coronation Street"><b>Coronation Street S56E215</b></a> "Mon Oct 26 2015 Part 2"</li><li><a href="/epsbyshow/13806/Crazy Ex-Girlfriend"><b>Crazy Ex-Girlfriend S01E03</b></a> "I Hope Josh Comes to My Party!"</li><li><a href="/epsbyshow/785/Dancing with the Stars"><b>Dancing with the Stars S21E09</b></a> "Week 7"</li><li><a href="/epsbyshow/17202/Dash Dolls"><b>Dash Dolls S01E06</b></a> "Dash Dolls Take New York"</li><li><a href="/epsbyshow/849/Days of our Lives"><b>Days of our Lives S51E26</b></a> "Monday October 26, 2015"</li><li><a href="/epsbyshow/18075/De Bunker"><b>De Bunker S01E09</b></a> "Aflevering 9"</li><li><a href="/epsbyshow/15896/De Rechtbank"><b>De Rechtbank S05E09</b></a> "Episode 9"</li><li><a href="/epsbyshow/11578/De Slimste Mens ter Wereld"><b>De Slimste Mens ter Wereld S13E09</b></a> "Aflevering 9"</li><li><a href="/epsbyshow/192/Doc Martin"><b>Doc Martin S07E07</b></a> "Facta Non Verba"</li><li><a href="/epsbyshow/1851/Doctors"><b>Doctors S17E123</b></a> "Where There's Hope"</li><li><a href="/epsbyshow/11470/Dokter Tinus"><b>Dokter Tinus S04E06</b></a> "Onverwachts gezelschap"</li><li><a href="/epsbyshow/1557/Dr. Phil"><b>Dr. Phil S14E31</b></a> "A Baby on the Way: "I Think My Daughter & Her Fiancé Are Unfit Parents & I Am Fighting for Custody o"</li><li><a href="/epsbyshow/763/Emmerdale"><b>Emmerdale S46E245</b></a> "Mon 26 Oct 2015"</li><li><a href="/epsbyshow/13413/Faking It"><b>Faking It S02E19</b></a> "The Deep End"</li><li><a href="/epsbyshow/12804/Fargo"><b>Fargo S02E03</b></a> "The Myth Of Sisyphus"</li><li><a href="/epsbyshow/18044/For My Man"><b>For My Man S01E07</b></a> "Tia Skinner/ Renyatta Hamilton"</li><li><a href="/epsbyshow/16547/Fractie, De"><b>Fractie, De S02E09</b></a> "Aflevering 9"</li><li><a href="/epsbyshow/17819/Girl Code Live"><b>Girl Code Live S01E09</b></a> "Episode 9"</li><li><a href="/epsbyshow/3567/Goede Tijden, Slechte Tijden"><b>Goede Tijden, Slechte Tijden S26E41</b></a> "Aflevering 5226"</li><li><a href="/epsbyshow/13550/Gotham"><b>Gotham S02E06</b></a> "Rise of the Villains: By Fire"</li><li><a href="/epsbyshow/11004/Gravity Falls"><b>Gravity Falls S02E18</b></a> "Weirdmageddon (1)"</li><li><a href="/epsbyshow/1770/Hagane no Renkinjutsushi (2003)"><b>Hagane no Renkinjutsushi (2003) S00E00</b></a> "N"</li><li><a href="/epsbyshow/13887/Have You Been Paying Attention?"><b>Have You Been Paying Attention? S04E25</b></a> "Episode 25"</li><li><a href="/epsbyshow/2748/Hollyoaks"><b>Hollyoaks S21E212</b></a> "October 26, 2015"</li><li><a href="/epsbyshow/922/Home and Away"><b>Home and Away S28E191</b></a> "Episode 6311"</li><li><a href="/epsbyshow/8078/House Hunters"><b>House Hunters S106E18</b></a> "Husband / Agent Tries to Find House for Picky Wife in Baltimore"</li><li><a href="/epsbyshow/8079/House Hunters International"><b>House Hunters International S85E18</b></a> "Two Schools of Thought in Lund"</li><li><a href="/epsbyshow/10198/Ikke gjør dette hjemme"><b>Ikke gjør dette hjemme S04E01</b></a> "1:8"</li><li><a href="/epsbyshow/14427/Jane the Virgin"><b>Jane the Virgin S02E03</b></a> "Chapter Twenty-Five"</li><li><a href="/epsbyshow/3775/Jeopardy!"><b>Jeopardy! S2015E183</b></a> "Episode 183"</li><li><a href="/epsbyshow/417/Jimmy Kimmel Live"><b>Jimmy Kimmel Live S2015E142</b></a> "Kristen Wiig, Ed Westwick, Elle King"</li><li><a href="/epsbyshow/14894/Ladies of London"><b>Ladies of London S02E08</b></a> "Something Rotten in Denmark"</li><li><a href="/epsbyshow/1674/Last Call with Carson Daly"><b>Last Call with Carson Daly S2015E81</b></a> "Mike Rowe, Wolf Alice, Welcome To Leith"</li><li><a href="/epsbyshow/13575/Late Night with Seth Meyers"><b>Late Night with Seth Meyers S2015E134</b></a> "Clive Owen, Rachel Dratch, Tim Gunn, Jeremy Gara"</li><li><a href="/epsbyshow/8544/Made in Chelsea"><b>Made in Chelsea S10E02</b></a> "Episode 2"</li><li><a href="/epsbyshow/3904/Media Watch"><b>Media Watch S2015E39</b></a> "2015-10-26"</li><li><a href="/epsbyshow/15803/Minority Report"><b>Minority Report S01E06</b></a> "Fiddler's Neck"</li><li><a href="/epsbyshow/3187/Murdoch Mysteries"><b>Murdoch Mysteries S09E03</b></a> "Double Life"</li><li><a href="/epsbyshow/472/Neighbours"><b>Neighbours S31E211</b></a> "Episode 7241"</li><li><a href="/epsbyshow/18220/One-Punch Man"><b>One-Punch Man S01E04</b></a> "The Modern Ninja"</li><li><a href="/epsbyshow/6207/Only Connect"><b>Only Connect S11E16</b></a> "Scientists v Athenians"</li><li><a href="/epsbyshow/17695/Pickle and Peanut"><b>Pickle and Peanut S01E14</b></a> "Busted Arm"</li><li><a href="/epsbyshow/17695/Pickle and Peanut"><b>Pickle and Peanut S01E13</b></a> "Cookie Racket"</li><li><a href="/epsbyshow/14496/Scorpion"><b>Scorpion S02E06</b></a> "Tech, Drugs, and Rock 'n Roll"</li><li><a href="/epsbyshow/4067/SpangaS"><b>SpangaS S09E41</b></a> "Episode #9.41"</li><li><a href="/epsbyshow/13723/Stacey Dooley Investigates"><b>Stacey Dooley Investigates S01E22</b></a> "World's Worst Place to Be a Woman"</li><li><a href="/epsbyshow/12927/Street Outlaws"><b>Street Outlaws S05E14</b></a> "Kansas City Barbecue"</li><li><a href="/epsbyshow/17771/Street Outlaws: Full Throttle"><b>Street Outlaws: Full Throttle S03E24</b></a> "When Life Gives You Lemons"</li><li><a href="/epsbyshow/15881/Supergirl"><b>Supergirl S01E01</b></a> "Pilot"</li><li><a href="/epsbyshow/8141/Switched at Birth"><b>Switched at Birth S04E20</b></a> "And Always Searching for Beauty"</li><li><a href="/epsbyshow/18024/Tavis Smiley"><b>Tavis Smiley S12E198</b></a> "Dr. Freeman Hrabowski"</li><li><a href="/epsbyshow/1115/The Big Bang Theory"><b>The Big Bang Theory S09E06</b></a> "The Helium Insufficiency"</li><li><a href="/epsbyshow/1483/The Biggest Loser (AU)"><b>The Biggest Loser (AU) S10E20</b></a> "Episode 20"</li><li><a href="/epsbyshow/17083/The Disappearance of Nagato Yuki-chan"><b>The Disappearance of Nagato Yuki-chan S01E00</b></a> "OVA"</li><li><a href="/epsbyshow/652/The Ellen DeGeneres Show"><b>The Ellen DeGeneres Show S2015E141</b></a> "Anthony Anderson, Gwen Stefani, Bindi Irwin & Derek Hough"</li><li><a href="/epsbyshow/650/The Gadget Show"><b>The Gadget Show S24E06</b></a> "Episode 6"</li><li><a href="/epsbyshow/16377/The Late Late Show with James Corden"><b>The Late Late Show with James Corden S2015E96</b></a> "Luke Wilson, Travis Mills"</li><li><a href="/epsbyshow/14901/The Late Show with Stephen Colbert"><b>The Late Show with Stephen Colbert S2015E30</b></a> "Sienna Miller, Melissa Benoist, Chance the Rapper"</li><li><a href="/epsbyshow/17518/The Real"><b>The Real S02E31</b></a> "Mark Paul Gosselaar, Vanessa Lachey, Tone Bell, Bresha Webb"</li><li><a href="/epsbyshow/1864/The Real Housewives Of Orange County"><b>The Real Housewives Of Orange County S10E21</b></a> "Reunion, Part Two"</li><li><a href="/epsbyshow/15860/The Secret Life of Books"><b>The Secret Life of Books S02E03</b></a> "The Mill on the Floss"</li><li><a href="/epsbyshow/12082/The Steve Wilkos Show"><b>The Steve Wilkos Show S09E26</b></a> "TBA"</li><li><a href="/epsbyshow/9979/The Talk"><b>The Talk S06E31</b></a> "Elyes Gabel, Robert Patrick, Ari Stidham, Eddie Kaye Thomas, Jaymes Vaughan"</li><li><a href="/epsbyshow/13574/The Tonight Show Starring Jimmy Fallon"><b>The Tonight Show Starring Jimmy Fallon S2015E168</b></a> "David Spade, Mike Tyson, Blake Shelton"</li><li><a href="/epsbyshow/4691/The View"><b>The View S2015E35</b></a> "Sen. Bernie Sanders, Wendi McLendon-Covey"</li><li><a href="/epsbyshow/8081/The Voice"><b>The Voice S09E11</b></a> "The Knockouts Premiere (1)"</li><li><a href="/epsbyshow/5900/The Wendy Williams Show"><b>The Wendy Williams Show S2015E31</b></a> "Robyn Moreno, Rob Shuter"</li><li><a href="/epsbyshow/7139/The X Factor (AU)"><b>The X Factor (AU) S07E19</b></a> "Top 8 Perform"</li><li><a href="/epsbyshow/1654/The Young and the Restless"><b>The Young and the Restless S43E40</b></a> "October 26, 2015"</li><li><a href="/epsbyshow/17675/This Life (CA)"><b>This Life (CA) S01E03</b></a> "The Part That Decides My Fate"</li><li><a href="/epsbyshow/4166/Thuis"><b>Thuis S21E41</b></a> "Aflevering 3851"</li><li><a href="/epsbyshow/1168/Traffic Cops"><b>Traffic Cops S13E05</b></a> "Cops & Robbers"</li><li><a href="/epsbyshow/13422/Uncle Grandpa"><b>Uncle Grandpa S02E50</b></a> "Fool Moon"</li><li><a href="/epsbyshow/15215/Vegas Rat Rods"><b>Vegas Rat Rods S02E05</b></a> "Stampede Rod"</li><li><a href="/epsbyshow/12732/Wander Over Yonder"><b>Wander Over Yonder S02E14</b></a> "The Battle Royale"</li><li><a href="/epsbyshow/5779/Watch What Happens: Live"><b>Watch What Happens: Live S12E172</b></a> "Wendi McLendon-Covey, Alexis Bellino"</li><li><a href="/epsbyshow/11027/Wheel of Fortune"><b>Wheel of Fortune S2015E148</b></a> "Halloween (1)"</li><li><a href="/epsbyshow/18222/WITS Academy"><b>WITS Academy S01E15</b></a> "Wonky Andi"</li><li><a href="/epsbyshow/36/WWE Monday Night RAW"><b>WWE Monday Night RAW S24E07</b></a> "Valley View Casino, San Diego, CA"</li><li><a href="/epsbyshow/8974/Yuru Yuri"><b>Yuru Yuri S03E04</b></a> "YuruYuri San☆Hai!: Episode 4"</li><li><a href="/epsbyshow/15907/Восьмидесятые"><b>Восьмидесятые S05E01</b></a> "Сезон 5, Серия 01"</li><li><a href="/epsbyshow/8182/Интерны"><b>Интерны S04E259</b></a> "Серия 259"</li><li><a href="/epsbyshow/18197/Квест"><b>Квест S01E01</b></a> "Серия 1"</li><li><a href="/epsbyshow/18115/Клан ювелиров"><b>Клан ювелиров S03E12</b></a> "3-12 Предательство. Серия 51"</li></ul>		<br>
                                            		<div align="center" style="font-size: xx-small; font-family: Verdana,Arial,Helvetica,Geneva,Swiss,Sans-Serif; clear: both;">
                                            			&copy; 2000-2015 <a href="mailto:contact@myepisodes.com">MyEpisodes</a>. All rights reserved. Design &copy; <a href="mailto:xxmwxx@spymac.com"><u>MW</u></a>.<br>
                                            			
                                            Online Users:[265] Online Guests:[400] User Total:[116908]<br>Page generated in 0.015441 seconds		</div>
                                            	</div>
                                            			</td>
                                            			<td width="50%">
                                            			</td>
                                            		</tr>
                                            	</table>
                                            	</BODY>
                                            </HTML>
11:20:29 T:8476  NOTICE: Storing total System Uptime
11:20:29 T:8476  NOTICE: Saving settings
11:20:29 T:8476  NOTICE: stop all
11:20:29 T:8476  NOTICE: stop player
11:20:29 T:8476  NOTICE: ES: Stopping event server
11:20:29 T:8476  NOTICE: stopping upnp
11:20:29 T:6540  NOTICE: ES: UDP Event server stopped
11:20:29 T:8476  NOTICE: stop sap announcement listener
11:20:29 T:8476  NOTICE: clean cached files!
11:20:29 T:8476  NOTICE: unload skin
11:20:34 T:6528 WARNING: CPythonInvoker(2, C:\Users\Łukasz\AppData\Roaming\Kodi\addons\service.skin.widgets\default.py): the python script "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\service.skin.widgets\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::Window,class PythonBindings::XBMCAddon_xbmc_Player_Director,class PythonBindings::XBMCAddon_xbmc_Monitor_Director
11:20:34 T:7608 WARNING: CPythonInvoker(7, C:\Users\Łukasz\AppData\Roaming\Kodi\addons\service.library.data.provider\service.py): the python script "C:\Users\Łukasz\AppData\Roaming\Kodi\addons\service.library.data.provider\service.py" has left several classes in memory that we couldn't clean up. The classes include: class PythonBindings::XBMCAddon_xbmc_Monitor_Director,class XBMCAddon::xbmcgui::Window,class PythonBindings::XBMCAddon_xbmc_Player_Director
11:20:35 T:3664  NOTICE: script.tv.show.next.aired: ### abort requested -- stopping background processing
11:20:35 T:8476  NOTICE: stopped
11:20:35 T:8476  NOTICE: destroy
11:20:35 T:8476  NOTICE: closing down remote control service
11:20:35 T:8476  NOTICE: unload sections
11:20:35 T:8476  NOTICE: special://profile/ is mapped to: special://masterprofile/
11:20:35 T:8476  NOTICE: destroy
11:20:35 T:8476 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
11:20:35 T:8476 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
11:20:35 T:8476  NOTICE: closing down remote control service
11:20:35 T:8476  NOTICE: unload sections
11:20:35 T:8476  NOTICE: application stopped...
11:20:35 T:8476   ERROR: dllFreeLibrary - Invalid hModule specified
```

And it seems to be logged in but in Kodi still authentiction failed...

**Comment by maximeh** [comment]
Indeed you are logged... The check to see if you are logged is really
simple, I check if your login is in the page. And cleary your login aXe is
in the page... I don't really get why it would display that you are not
logged.

**Comment by misiaty** [comment]
:)

I think I got it.
I've changed my username to 'aXe' in kodi and now it says 'connected'. Now I'm checking and via web site I'm logging as 'axe' - all i small characters.

**Comment by maximeh** [comment]
Ahhh ! Okey. That's nice to know, I'll add some complementary check for the
casing then.

**Comment by maximeh** [comment]
I've prepared a 1.2.5 which should take care of that issue for you. If you want to give it a spin, that would be great.

So that I can close this issue :)

**Comment by misiaty** [comment]
Now it's working like a charm. :)

**Comment by maximeh** [comment]
Nice to know. Thanks a lot for your efforts ! I'm closing this then.
